### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by kach** [bobbybee/uPresent#2]
- [x] Proper ul/li-based lists
- [x] Proper slide navigation, using arrow keys, so that I can go forward _and_ back. It needs to work with one of those wireless clickey things that speakers on stage use.
- [x] Use p tags instead of brs all over the place.
- [x] Use em for italics and strong for bold, instead of b and i tags. b and i are deprecated, and I can control typography better with em and strong.
- [ ] I'll take care of prettifying the CSS.

**Comment by alyssarosenzweig** [comment]
Slide navigation will be addressed in #3 

Please review :)

**Comment by alyssarosenzweig** [comment]
`p`, `em`, and `strong` tags used in PR #4 

Also review :)

**Comment by tjvr** [comment]
> I'll take care of prettifying the CSS.

[Times New Roman](https://github.com/bobbybee/uPresent/blob/master/style.css#L8) ain't very pretty. :P

**Comment by alyssarosenzweig** [comment]
#5 addresses ul/li lists-- @blob8108 @Hardmath123 please review!
