### ISSUE TITLE
Fix inconsistent tabs

### ISSUE THREAD

**Issue by alyssarosenzweig** [bobbybee/uPresent#29]
Not sure what settings @Hardmath123 uses, but there's a lot of inconsistencies which is ugly. We probably need a style guide for the project.

**Comment by alyssarosenzweig** [comment]
#31 cleans this up

**Comment by kach** [comment]
4 spaces make the world, go 'round, Alyssa, tabby people are crabby people.

**Comment by alyssarosenzweig** [comment]
@Hardmath123 OK... explanation + how to change in vim?

**Comment by kach** [comment]
Fair enough.

``` viml
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
```

Use `gg=G` to reindent a file.

**Comment by kach** [comment]
Oh, and protip, set up `autocmd FileType make setlocal noexpandtab` so that Makefiles don't trip you up (they require tabs instead of spaces).

**Comment by alyssarosenzweig** [comment]
Done <3
