### ISSUE TITLE
Horizontal scrollbars appear when viewing presentations

### ISSUE THREAD

**Issue by antiprime** [bobbybee/uPresent#35]
Tested in Firefox/Iceweasel 38.0.1

![Screenshot](https://cloud.githubusercontent.com/assets/1058877/7899368/10070ab2-06d5-11e5-8843-998553898f66.png)

**Comment by alyssarosenzweig** [comment]
Neither horizontal nor vertical scrollbars should be appearing. I'll look into it.

**Comment by alyssarosenzweig** [comment]
The example was running an old version of the code.Recompiled and repushed; the issue should be gone :)
