### ISSUE TITLE
Function keys are overridden

### ISSUE THREAD

**Issue by antiprime** [bobbybee/uPresent#36]
Pressing F1-F12 moves to the next slide instead of performing the key's intended function.

**Comment by alyssarosenzweig** [comment]
@nickolas360 What should they be doing instead?

**Comment by antiprime** [comment]
Opening the browser's help, refreshing the page, toggling caret browsing (in Firefox), toggling fullscreen, etc.

**Comment by alyssarosenzweig** [comment]
@nickolas360 Would you mind getting the key code values for the keys from http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes ?

My fn keys are inconsistent with the table here. Perhaps this is shadowing a larger issue regarding the UI itself?

**Comment by antiprime** [comment]
Function keys still aren't working for me. Has the demo been updated?

**Comment by alyssarosenzweig** [comment]
@nickolas360 Probably not. http://upresent.js.org/www/demo/demo.html#slide0 is the latest IIRC

**Comment by antiprime** [comment]
Function keys aren't working with that one either.
