### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ninjagolloyd** [bobbybee/uPresent#42]
- [x] Add support for Windows

**Comment by alyssarosenzweig** [comment]
I don't have access to a Windows machine, so I can't test it. However, uPresent doesn't use any platform specific code to my knowledge, so it should work :)

**Comment by alyssarosenzweig** [comment]
Furthermore, uPresent has experimental builds targeting the browser itself, eliminating the platform issue entirely.

**Comment by alyssarosenzweig** [comment]
@zippynk and I are working to bring Windows support to uPresent natively. A few bugs are being worked out, but it should work soon :)

**Comment by ninjagolloyd** [comment]
The .sh file is for Bash, which is for Linux.

**Comment by alyssarosenzweig** [comment]
@ninjagolloyd This is correct; however, to simply use uPresent (and not hack on it), it is _not_ necessary to use this script. We're working on a patch to make this script only necessary for developers (who should be using Linux / OS X anyway)

**Comment by ninjagolloyd** [comment]
Oh OK
I should really find a way to get Linux. I do not have admin privs so I can't do a lot of stuff it is weird

**Comment by alyssarosenzweig** [comment]
@ninjagolloyd Regardless, the web version of uPresent should be ready very soon :)

**Comment by ninjagolloyd** [comment]
Yay!!!!!!!!!!!!!!!!!!!

**Comment by alyssarosenzweig** [comment]
@ninjagolloyd If you're interested in the bleeding edge version, clone uPresent, switch to the `feature/web-editor` branch, cd into the root uPresent directory, and then type `python -m SimpleHTTPServer 8080`. Note, this requires python (2) to be installed.

Then, from your web browser, navigate [here](http://localhost:8080/browser/IDE/ide.html) for the IDE--- or, if you're feeling adventurous, [here](http://location:8080/target/target.html) for just the compiler without the IDE ;)

**Comment by alyssarosenzweig** [comment]
@ninjagolloyd Scratch that... http://bobbybee.github.io/uPresent/browser/IDE/ide.html :)

**Comment by ninjagolloyd** [comment]
Yay!
