### ISSUE TITLE
Um... Pronunciation issues?

### ISSUE THREAD

**Issue by ninjagolloyd** [bobbybee/uPresent#45]
The Ελληνικά letter μ sounds like /moo/ so isn't it pronounced /moo present/? lol :yum:

**Comment by alyssarosenzweig** [comment]
I assume you're from the United Kingdom?

Wiktionary seems to suggest that /moo/ is the UK (probably also rest of the world) pronounication, where as /myoo/ is the pronounciation in the United States.

As for what the _actual_ pronounication is/was in Ελληνικά, well... it's all Greek to me.

**Comment by ninjagolloyd** [comment]
Nope. American. And it is /moo/. Unfortunately, I tried learning Greek. It was hard.

**Comment by ninjagolloyd** [comment]
And it is /moo/. Unfortunately, I tried learning Greek.

**Comment by ninjagolloyd** [comment]
It was hard.

**Comment by alyssarosenzweig** [comment]
I reread the README, and I think I understand the confusion: μ is pronounced micro is some contexts. Our pronounication and choice of the μ letter in the name comes from units like μm, the micrometre, 10^-6 of a meter. :)

**Comment by ninjagolloyd** [comment]
oh
